pipeline {
    agent any
    stages {
        stage("Clean Up") {
            steps {
                deleteDir();
            }

        }

        stage("Clone Repo") {
            steps {
                sh "git clone https://github.com/anhquan0/simple-java-maven-app.git"
            }
        }

        stage("Build") {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn clean install"
                }
            }
        }

        stage("Test") {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn test"
                }
            }
        }

        stage('Deliver') {
            steps {
                sh "ls"
                sh './jenkins/scripts/deliver.sh'
            }
        }

        stage('Complete') {
            steps {
                sh 'Ok'
            }
        }
    }

}